version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4  # Usamos una imagen oficial con PostgreSQL 16 y PostGIS 3.4
    restart: always
    environment:
      - POSTGRES_USER=user_dev
      - POSTGRES_PASSWORD=password_dev
      - POSTGRES_DB=directorio_local_db
    ports:
      - '5433:5432' # Mapeamos el puerto 5432 del contenedor al 5433 de tu máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data # Esto guarda los datos para que no se pierdan

volumes:
  postgres_data: