# Usa una imagen base de Node.js
FROM node:20-alpine AS frontend-dev

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia todos los archivos de Next.js (app, public, etc.)
COPY . .

# Puerto por defecto de Next.js
EXPOSE 3000

# El comando de inicio será gestionado por docker-compose.yml
# CMD ["npm", "run", "dev:frontend"]